---
- name: Create an Azure Key Vault Secret
  hosts: localhost
  connection: local

  vars:
    # provide unique name for key vault
    vault_name: <vault name>
    kv_resource_group_name: awesomekvrg

  tasks:

  - name: Get Key Vault by name
    azure_rm_keyvault_info:
      resource_group: "{{ kv_resource_group_name }}"
      name: "{{ vault_name }}"
    register: keyvault

  - debug:
      msg: '{{ keyvault }}'

  - name: set KeyVault uri fact
    set_fact: keyvaulturi="{{ keyvault | json_query('keyvaults[0].vault_uri')}}"
    
  - debug:
      msg: '{{ keyvaulturi }}' 

  - name: Create a secret
    azure_rm_keyvaultsecret:
      secret_name: localAdminPassword1
      secret_value: Aw3s0meP@ssw0rd
      keyvault_uri: "{{ keyvaulturi }}"