---
- name: Test connection to Windows VM
  hosts: <host group name>
  connection: local
  
  collections:
    - azure.azcollection

  vars_prompt:
    - name: ansible_password
      prompt: "Enter local administrator password"

  vars:
    ansible_user: awesomeadmin
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
  
  tasks:
  - name: Test connection
    win_ping:
